/** User-facing copy. See writing-rules.md at project root. */
export const copy = {
  brand: {
    wordmark: 'zazu',
    tagline: 'A new word. Every morning.',
    pageTitle: 'Zazu. Wake up. Learn something.',
  },
  home: {
    wordOfDayEyebrow: 'Word of the day',
    wordOfDayLoading: 'Loading…',
    wordLibraryError:
      'Could not load words from the cloud. Using the built-in library for now.',
    wordLibraryRetry: 'Try again',
    yourAlarms: 'Your alarms',
    addAlarm: '+ Add alarm',
    tryTheAlarm: 'Try the alarm',
    dayStreak: 'day streak',
    weekdaysPack: 'Weekdays · Words pack',
    weekendsPack: 'Weekends · Words pack',
    tabHome: 'Home',
    tabGym: 'Word Gym',
    tabVocabulary: 'Vocabulary',
  },
  alarm: {
    todaysWord: "Today's word",
    learnSub: 'Learn it, then one quick question',
    wakeCta: "I'm awake. Let's go.",
  },
  learn: {
    eyebrow: 'Learn the word',
    etymology: 'Etymology',
    continue: 'Continue',
  },
  morningTask: {
    eyebrow: 'Morning task',
    spellPrompt: "Spell today's word",
    findPrompt: "Tap the word below that matches",
    dismiss: 'Dismiss alarm',
    tryAgain: 'Not quite. Try again.',
    hintClue: (definition: string) => `Hint: it means ${definition}`,
    hintReveal: "It's glowing below.",
    hintRevealScreenReader: (word: string) => `It's "${word}". Select it from the list below.`,
  },
  alarmPermissions: {
    bannerTitle: "Alarm can't wake a locked phone yet",
    bannerBody: 'Grant these so it fires and shows through the lock screen.',
    notifications: 'Allow notifications',
    exactAlarm: 'Allow exact alarms',
    battery: 'Allow background activity',
    fix: 'Fix',
  },
  addAlarm: {
    title: 'Add alarm',
    timeLabel: 'Time',
    labelLabel: 'Label',
    labelPlaceholder: 'e.g. Work',
    soundLabel: 'Sound',
    soundPreviewA11y: (name: string) => `Preview ${name}`,
    save: 'Save alarm',
    cancel: 'Cancel',
    deleteTitle: 'Delete alarm?',
    deleteMessage: (time: string) => `Delete the ${time} alarm? This can't be undone.`,
    deleteConfirm: 'Delete',
  },
  ad: {
    eyebrow: 'One quick message',
    pill: 'Ad. Keeps Zazu free.',
    brand: 'Huel Black Edition',
    copy: 'Complete nutrition in 90 seconds. Ideal for mornings when breakfast isn\'t happening. Try the starter kit. First order 20% off.',
    cta: 'Find out more',
    skip: 'Skip →',
  },
  onboarding: {
    noAccountNeeded: 'No account needed to start. Sign in later to save progress across devices.',
    getStarted: 'Get started',
    alreadyHaveAccount: 'Already have an account?',
    progressSaved: 'Your progress will sync when you sign in.',
    googleNotConfigured: 'Google sign-in is not configured in this build.',
    nameHeading: 'What should we call you?',
    namePlaceholder: 'Your name',
    nameConfirm: 'Continue',
  },
  settings: {
    back: 'Go back',
    title: 'Settings',
    signedInAs: (name: string) => `Signed in as ${name}`,
    guestMode: 'Guest mode',
    guestHint: 'Sign in to sync streak, coins, and Gold across devices.',
    goldMember: 'Zazu Gold member',
    freePlan: 'Free plan',
    manageGold: 'Manage Gold',
    upgradeGold: 'Upgrade to Gold',
    signOut: 'Sign out',
    signIn: 'Sign in',
    themeAuto: 'Theme: Auto (Dawn/Dusk)',
    themeLight: 'Theme: Light',
    themeDark: 'Theme: Dark',
    themeToggleHint: 'Cycles between Auto, Light, and Dark themes.',
  },
  gold: {
    eyebrow: 'Zazu Gold',
    title: 'Wake up to everything',
    subtitle: 'Full word history, Word Gym, and more.',
    features: [
      'Full calendar word history',
      'Word Gym on every past word',
      'Support Zazu development',
    ],
    trialBadge: '7-day trial',
    subscribe: 'Start free trial',
    restore: 'Restore purchases',
    restoreNone: 'No previous purchase found.',
    signInRequired: 'Sign in to subscribe.',
    setupRequired: 'Purchases are not configured in this build.',
    alreadyGold: 'You\'re on Gold',
    alreadyGoldSub: 'Thanks for supporting Zazu.',
  },
  success: {
    heading: "You're up.",
    sub: 'One new word. Carry it with you today.',
    wordLearned: 'Word learned',
    coinsEarned: 'Coins earned',
    puzzleCompleted: 'Puzzle completed',
    morningTaskCompleted: 'Morning task completed',
    noSnooze: 'No snooze',
    streakBonus: 'Streak bonus',
    total: 'Total',
    done: 'Done',
    streakCount: (n: number) => `${n} day streak!`,
    streakSubtitle: (title: string) => `${title}. Keep it going tomorrow.`,
    shareCta: 'Share this word',
    shareMessage: (word: string, definition: string) =>
      `${word}: ${definition}\n\nLearned it with Zazu, one word a day.`,
  },
  puzzle: {
    roundLabel: (round: number, type: string) => `Round ${round} of 3 · ${type}`,
    emptyPlaceholder: '–',
    saving: 'Saving your progress…',
  },
  gym: {
    eyebrow: 'Word Gym',
    todaysWord: "Today's practice word",
    subtitle: 'Three rounds to lock it in',
    mastery: 'Mastery',
    masteryComplete: 'Completed today',
    masteryNew: 'Not practised yet',
    start: 'Start practice',
    continue: 'Practise again',
    goldModesTitle: 'More practice',
    goldModesSub: 'Review what you know and drill the words you have already learned.',
    unlockGoldLink: 'Unlock more practice modes with Zazu Gold',
  },
  gymModes: {
    reviewTitle: 'Review queue',
    reviewDescription: 'Practise words that are due for a refresh.',
    reviewEmpty: 'Nothing due yet. Come back after learning more words.',
    reviewBadge: (n: number) => `${n} due`,
    rootsTitle: 'Roots drill',
    rootsLabel: 'Roots drill',
    rootsDescription: 'Match roots to their meanings across words you know.',
    usageTitle: 'Usage lab',
    usageLabel: 'Usage lab',
    usageDescription: 'Complete sentences using words you have already learned.',
    needLearnedWords: 'Learn a few words first to unlock this.',
    questionProgress: (current: number, total: number) => `Question ${current} of ${total}`,
    mcqHint: (word: string) => `Have another look, then try ${word} again.`,
    checkCta: 'Check',
    nextCta: 'Next',
    retryCta: 'Retry',
    correctFeedback: 'Nicely done!',
    wrongFeedback: 'Not quite',
    literaryTitle: 'Literary words',
    literaryDescription: 'Quotes and coinages from Shakespeare, Milton, Dickens and more.',
    literaryEmpty: 'No literary words yet.',
  },
  dailyRitual: {
    eyebrow: 'Daily ritual',
    successCta: "Go deeper on today's word?",
    successCtaSub: "A few quick questions, just about today's word. No pressure, always free.",
    start: 'Try it',
    skip: 'Not now',
    heading: 'Nicely done.',
    sub: 'One more small win before the day starts.',
    coinsEarned: 'Coins earned',
    alreadyDoneToday: 'Already done for today. Come back tomorrow for a new word.',
    done: 'Done',
    saving: 'Saving your progress…',
  },
  gymSuccess: {
    heading: 'Well practised.',
    sub: 'Three rounds done. That word should stick.',
    wordPractised: 'Word practised',
    masteryLabel: 'Mastery',
    coinsEarned: 'Coins earned',
    gymCompleted: 'Word Gym completed',
    total: 'Total',
    done: 'Done',
    masteryPercent: (n: number) => `${n}% mastery`,
  },
  placeholder: {
    matutinalOrigin:
      'From Latin matutinus, of the morning, from Matuta, the Roman goddess of the dawn.',
  },
  a11y: {
    streak: (n: number) => `${n} day streak`,
    coins: (n: number) => `${n} coins`,
    wordOfDay: (word: string, definition: string) => `Word of the day: ${word}. ${definition}`,
    alarmToggle: (time: string, enabled: boolean) => `Alarm ${time}, ${enabled ? 'on' : 'off'}`,
    deleteAlarm: (time: string) => `Delete alarm ${time}`,
  },
  calendar: {
    title: 'Vocabulary',
    yourWordsSection: 'Your words',
    wordPacksSection: 'Word packs',
    wordPacksSub: 'Deeper vocabulary, unlocked with Zazu Gold.',
    comingSoon: 'Coming soon',
    wordsLearned: (n: number) => `${n} word${n === 1 ? '' : 's'} learned`,
    streakDays: (n: number) => `${n} day${n === 1 ? '' : 's'}`,
    previewAs: 'Preview as:',
    freeUser: 'Free user',
    goldUser: 'Zazu Gold',
    today: 'Today',
    monthWordCount: (n: number) => `${n} word${n === 1 ? '' : 's'}`,
    done: 'Done',
    gym: 'Gym',
    gold: 'Gold',
    skipped: 'skipped',
    unlockGold: 'Unlock with Zazu Gold ↗',
    goldPricing: '£2.49/month or £14.99/year · 7-day free trial',
    morningTask: 'Morning task',
    gotFirstTry: 'Got it first try',
    neededHint: 'Needed one hint',
    streakDayOf: (n: number) => `Day ${n} of your current streak`,
    timeToDismiss: 'Time to dismiss',
    alarmToDone: 'alarm to done',
    coinsEarned: 'Coins earned',
    thatMorning: 'that morning',
    wordGym: 'Word Gym',
    goldFeature: 'Zazu Gold feature',
    unlock: 'Unlock ↗',
    gymCompleted: 'Word Gym completed',
    gymNotDone: 'Word Gym not done that day',
    openGym: 'Open in Word Gym',
    sheetDone: 'Done',
    notCompleted: '–',
    unlockMissedTitle: (word: string) => word,
    unlockMissedMessage: (cost: number) => `Unlock this word for ${cost} coins?`,
    unlockMissedConfirm: (cost: number) => `Unlock (${cost} coins)`,
    unlockMissedCancel: 'Cancel',
    insufficientCoinsTitle: 'Not enough coins',
    insufficientCoinsMessage: (have: number, need: number) => `You have ${have}, need ${need}.`,
  },
  vocabulary: {
    packWordCount: (n: number) => `${n} word${n === 1 ? '' : 's'}`,
    openInGym: 'Open in Word Gym',
    empty: 'No words in this pack yet.',
  },
} as const;
