/** User-facing copy. See writing-rules.md at project root. */
export const copy = {
  brand: {
    wordmark: 'zazu',
    tagline: 'A new word. Every morning.',
    pageTitle: 'Zazu. Wake up. Learn something.',
  },
  home: {
    wordOfDayEyebrow: 'Word of the day',
    wordOfDayLoading: 'Loading…',
    wordLibraryError:
      'Could not load words from the cloud. Using the built-in library for now.',
    wordLibraryRetry: 'Try again',
    yourAlarms: 'Your alarms',
    addAlarm: '+ Add alarm',
    tryTheAlarm: 'Try the alarm',
    switchToLightMode: '☀️ Switch to light mode',
    switchToDarkMode: '🌙 Switch to dark mode',
    dayStreak: 'day streak',
    weekdaysPack: 'Weekdays · Words pack',
    weekendsPack: 'Weekends · Words pack',
    tabHome: 'Home',
    tabGym: 'Word Gym',
  },
  alarm: {
    goodMorning: 'Good morning',
    todaysWord: "Today's word:",
    learnSub: 'Learn it, then one quick question',
    wakeCta: "I'm awake. Let's go.",
  },
  learn: {
    eyebrow: 'Learn the word',
    etymology: 'Etymology',
    continue: 'Continue',
  },
  morningTask: {
    eyebrow: 'Morning task',
    dismiss: 'Dismiss alarm',
    tryAgain: 'Not quite. Try again.',
  },
  addAlarm: {
    title: 'Add alarm',
    timeLabel: 'Time',
    timePlaceholder: '07:30',
    labelLabel: 'Label',
    labelPlaceholder: 'Weekdays · Words pack',
    save: 'Save alarm',
    invalidTime: 'Enter a valid time like 07:30',
  },
  ad: {
    eyebrow: 'One quick message',
    pill: 'Ad. Keeps Zazu free.',
    brand: 'Huel Black Edition',
    copy: 'Complete nutrition in 90 seconds. Ideal for mornings when breakfast isn\'t happening. Try the starter kit. First order 20% off.',
    cta: 'Find out more',
    skip: 'Skip →',
  },
  onboarding: {
    noAccountNeeded: 'No account needed to start. Sign in later to save progress across devices.',
    getStarted: 'Get started',
    alreadyHaveAccount: 'Already have an account?',
    progressSaved: 'Your progress will sync when you sign in.',
    googleNotConfigured: 'Google sign-in is not configured in this build.',
    nameHeading: 'What should we call you?',
    namePlaceholder: 'Your name',
    nameConfirm: 'Continue',
  },
  settings: {
    back: 'Go back',
    title: 'Settings',
    signedInAs: (name: string) => `Signed in as ${name}`,
    guestMode: 'Guest mode',
    guestHint: 'Sign in to sync streak, coins, and Gold across devices.',
    goldMember: 'Zazu Gold member',
    freePlan: 'Free plan',
    manageGold: 'Manage Gold',
    upgradeGold: 'Upgrade to Gold',
    signOut: 'Sign out',
    signIn: 'Sign in',
  },
  gold: {
    title: 'Zazu Gold',
    subtitle: 'Full word history, Word Gym, and more.',
    features: [
      'Full calendar word history',
      'Word Gym on every past word',
      'Support Zazu development',
    ],
    subscribe: 'Start free trial',
    restore: 'Restore purchases',
    restoreNone: 'No previous purchase found.',
    signInRequired: 'Sign in to subscribe.',
    setupRequired: 'Purchases are not configured in this build.',
    alreadyGold: 'You\'re on Gold',
    alreadyGoldSub: 'Thanks for supporting Zazu.',
  },
  success: {
    heading: "You're up.",
    sub: 'One new word. Carry it with you today.',
    wordLearned: 'Word learned',
    coinsEarned: 'Coins earned',
    puzzleCompleted: 'Puzzle completed',
    morningTaskCompleted: 'Morning task completed',
    noSnooze: 'No snooze',
    streakBonus: 'Streak bonus',
    total: 'Total',
    done: 'Done',
    streakCount: (n: number) => `${n} day streak!`,
    streakSubtitle: (title: string) => `${title}. Keep it going tomorrow.`,
  },
  puzzle: {
    roundLabel: (round: number, type: string) => `Round ${round} of 3 · ${type}`,
    emptyPlaceholder: '–',
  },
  gym: {
    eyebrow: 'Word Gym',
    todaysWord: "Today's practice word",
    subtitle: 'Three rounds to lock it in',
    mastery: 'Mastery',
    masteryComplete: 'Completed today',
    masteryNew: 'Not practised yet',
    start: 'Start practice',
    continue: 'Practise again',
  },
  gymSuccess: {
    heading: 'Well practised.',
    sub: 'Three rounds done. That word should stick.',
    wordPractised: 'Word practised',
    masteryLabel: 'Mastery',
    coinsEarned: 'Coins earned',
    gymCompleted: 'Word Gym completed',
    total: 'Total',
    done: 'Done',
    masteryPercent: (n: number) => `${n}% mastery`,
  },
  placeholder: {
    matutinalOrigin:
      'From Latin matutinus, of the morning, from Matuta, the Roman goddess of the dawn.',
  },
  a11y: {
    streak: (n: number) => `${n} day streak`,
    coins: (n: number) => `${n} coins`,
    wordOfDay: (word: string, definition: string) => `Word of the day: ${word}. ${definition}`,
    alarmToggle: (time: string, enabled: boolean) => `Alarm ${time}, ${enabled ? 'on' : 'off'}`,
  },
  calendar: {
    title: 'Your words',
    wordsLearned: (n: number) => `${n} word${n === 1 ? '' : 's'} learned`,
    streakDays: (n: number) => `${n} day${n === 1 ? '' : 's'}`,
    previewAs: 'Preview as:',
    freeUser: 'Free user',
    goldUser: 'Zazu Gold',
    today: 'Today',
    thisWeek: 'This week',
    olderWords: 'Older words',
    done: 'Done',
    gym: 'Gym',
    gold: 'Gold',
    skipped: 'skipped',
    lockTitle: (n: number) => `${n} more word${n === 1 ? '' : 's'}, waiting for you`,
    lockSub: 'Unlock your full word history with Zazu Gold',
    unlockGold: 'Unlock with Zazu Gold ↗',
    goldPricing: '£3.99/month or £24.99/year · 7-day free trial',
    morningTask: 'Morning task',
    gotFirstTry: 'Got it first try',
    neededHint: 'Needed one hint',
    streakDayOf: (n: number) => `Day ${n} of your current streak`,
    timeToDismiss: 'Time to dismiss',
    alarmToDone: 'alarm to done',
    coinsEarned: 'Coins earned',
    thatMorning: 'that morning',
    wordGym: 'Word Gym',
    goldFeature: 'Zazu Gold feature',
    unlock: 'Unlock ↗',
    gymCompleted: 'Word Gym completed',
    gymNotDone: 'Word Gym not done that day',
    openGym: 'Open in Word Gym',
    sheetDone: 'Done',
    notCompleted: '–',
  },
} as const;
